apiVersion: apps/v1
kind: Deployment
metadata: 
  name: posts-depl
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: posts
  template: 
    metadata:
      labels:
        app: posts 
    spec:
      containers:
        - name: posts
          image: pinakinc/posts
          env:
            - name: POSTS_NATS_CLIENT_ID
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.name
            - name: POSTS_NATS_URL
              value: 'http://nats-srv:4222'
            - name: POSTS_NATS_CLUSTER_ID
              value: 'blog'
            - name: POSTS_MONGO_URI
              value: 'mongodb://posts-mongo-srv:27017/posts'
            - name: AUTH_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: AUTH_JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  selector:
    app: posts
  ports: 
    - name: posts
      protocol: TCP
      port: 3100
      targetPort: 3100    
